// Generated by ts-to-zod
import { z } from "zod";

export const sampleSchema = z.object({
  name: z.string(),
  email: z.string(),
  age: z.number(),
  is_adult: z.boolean(),
  gender: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  hobby: z.array(
    z.union([z.literal("game"), z.literal("books"), z.literal("sports")]),
  ),
});
